### ISSUE TITLE
Use autoloader for TestCase

### ISSUE THREAD

**Issue by davejamesmiller** [davejamesmiller/laravel-breadcrumbs#101]
Instead of https://github.com/davejamesmiller/laravel-breadcrumbs/blob/212d6bc26b4f617a542e2c1756cebf454895e098/phpunit.php

See https://github.com/alberon/awe/blob/bf9eaea09d72f2adc907944c82104b06b05c32f2/bootstrap/phpunit.php

**Comment by bahjaat** [comment]
Indeed. Has some multiple instances of TestCase at PHPStorm. Thanks. Version bumb?

**Comment by davejamesmiller** [comment]
@bahjaat Sorry, I have no idea what you're trying to say there...
