### ISSUE TITLE
attach/append to nested breadcrumbs end

### ISSUE THREAD

**Issue by szabizs** [davejamesmiller/laravel-breadcrumbs#106]
Hi,
I have this nested breadcrumb for categories that does work as intended.

```php
Breadcrumbs::register('product', function ($breadcrumbs,$category,$product) {
        if($category->parent) {
            $breadcrumbs->parent('product',$category->parent,$product);
        } else {
            /** Use this if you want a breadcrumb to Home **/
            $breadcrumbs->parent('home');
        }
        $breadcrumbs->parent('curretProductCategory',$category,$product);
        if($category->parent) {
            $breadcrumbs->push($product->name);
        }        
});
```

Here I have the `$product` object..
I want to add the `$product->title` at the end of the breadcrumb, this works when the product is in a level 2 category, if the product is in a level 3 category, then the product name is listed twice because of the recursion.

Could you point me out on this one please ? How can I attach/append the product title to the rendered breadcrumb as the last breadcrumb ?

Current output:  `Home > Category 1 > Child 1 > Product title > Child 1-1 > Product title`

Desired output: `Home > Category 1 > Child 1 > Child 1-1 > Product title`

**Comment by davejamesmiller** [comment]
To keep it simple, don't call 'parent' more than once in a callback, and create separate breadcrumbs for the products and the categories - don't try to combine them.

e.g.

```php
Breadcrumbs::register('category', function ($breadcrumbs, $category) {
    if ($category->parent)
        $breadcrumbs->parent('category', $category->parent);
    else
        $breadcrumbs->parent('home');

    $breadcrumbs->push($category->name);
});

Breadcrumbs::register('product', function ($breadcrumbs, $category, $product) {
    $breadcrumbs->parent('category', $category);
    $breadcrumbs->push($product->name);
});
```

**Comment by szabizs** [comment]
Oh, that was so obvious and simple :) :+1:  thank you!
