### ISSUE TITLE
Should pull request be done on master or develop branch?

### ISSUE THREAD

**Issue by anik786** [davejamesmiller/laravel-breadcrumbs#108]
Should pull request be done on master or develop branch?

On http://laravel-breadcrumbs.davejamesmiller.com/en/latest/contributing.html it says bug fixes should be done on the develop branch.

But what about things like changes that are not "bug fixes" but rather removing deprecated features, or improvements to docs?

**Comment by davejamesmiller** [comment]
I've updated the documentation to match the readme & removed the note about branches. Basically I've stopped using the develop branch and just do everything on master now, to keep things simple - so everything can go there. Thanks!
