### ISSUE TITLE
Laravel 5.2 Implicit Route Model Binding

### ISSUE THREAD

**Issue by fredrkr** [davejamesmiller/laravel-breadcrumbs#113]
Let's say that I do this in my breadcrumbs.php-file:

```php
Breadcrumbs::register('book.edit', function($breadcrumbs, $book){
    $breadcrumbs->parent('dashboard');
    $breadcrumbs->push($book->title);
});
```

I can access the 'book'-object here because I'm using route model binding. But in Laravel 5.2 we have something called *implicit* route model binding. That is, you just need to typehint the expected object in your controller-methods, like this:

```php
public function edit(App\Book $book){
    return $book;
}
```

... and I don't need to bind it explicitly in a service provider. The problem is that I can no longer access the 'book'-object from inside the closure in the Breadcrumbs register-call. As you'd expect, the $book-variable now only contains the url-parameter, which could be something like '2'. 

Will you add support for implicit route model binding? It could work the same way as controller-methods:

```php
Breadcrumbs::register('book.edit', function($breadcrumbs, App\Book $book){ });
```

**Comment by davejamesmiller** [comment]
That's definitely a good idea. I can't promise when I'll get to it myself (I'm not actively working on any Laravel projects at the moment so it's on the back-burner for a while), but I'd certainly accept a PR for it. (If no-one does make one, I'll make sure it's at the top of the feature list for the next version, when I get to it.)

I've not looked into how implicit model binding works - in fact I've not used it yet - but ideally I'd want to make sure it doesn't load the model from the database twice as a result of this.

**Comment by dlnsk** [comment]
@fredrkr Binding works in 5.2
```
Breadcrumbs::register('area.show', function($breadcrumbs, $area) {
	$breadcrumbs->parent('home');
	if (\Gate::allows('viewArea', $area)) {
		$breadcrumbs->push($area->title, route('area.show', $area->id));
	}
});
```

**Comment by fredrkr** [comment]
Yes, you're right. For some reason I was unable to get this to work when I tested it earlier. This issue can be safely closed :)
