### ISSUE TITLE
Ussing more than one template.

### ISSUE THREAD

**Issue by dgarcia-grupoz** [davejamesmiller/laravel-breadcrumbs#115]
Hi. I'm using this package and it's great. 

Now, I 'm trying to do something that I do not know if it's possible. 
I would like to use more than one template to show in different places.

It would be great if it were possible to send the template as an optional parameter.

**Comment by davejamesmiller** [comment]
Yes you can - it's not the prettiest code admittedly (a function with a view parameter would be better) but see http://laravel-breadcrumbs.davejamesmiller.com/en/latest/advanced.html#switching-views-dynamically

**Comment by dgarcia-grupoz** [comment]
I had not seen that.

Thank you!
