### ISSUE TITLE
$breadcrumbs is undefined in Blade

### ISSUE THREAD

**Issue by sinamiandashti** [davejamesmiller/laravel-breadcrumbs#116]
Hi

i cant use this in my  template

{{$breadcrumb->title}}

**Comment by davejamesmiller** [comment]
I'm not sure what you expect me to do with that information.

https://github.com/davejamesmiller/laravel-breadcrumbs#support-requests--bug-reports

**Comment by sinamiandashti** [comment]
lol

fixed by this : 

```
<?php

$bread = Breadcrumbs::generate();
$breadtitle = $bread[count($bread) - 1]->title;

?>{{$breadtitle}}
```
