### ISSUE TITLE
Route [home] not defined

### ISSUE THREAD

**Issue by avescasio** [davejamesmiller/laravel-breadcrumbs#117]
Hi Dave,
This is my first time to use laravel-breadcrumbs in my first project.

After installation and registering the class at config/app.php and followed the steps in your documentation I got: 

"Route [home] not defined. (View: D:\DEV\www\ek_crm\resources\views\industry\index.blade.php)" 

my code in app/Http/breadcrumbs.php:

`<?php 

// Home
Breadcrumbs::register('home', function($breadcrumbs)
{
    $breadcrumbs->push('Home', route('home'));
});

// Home > Industry
Breadcrumbs::register('industry', function($breadcrumbs)
{
    $breadcrumbs->parent('home');
    $breadcrumbs->push('Industry', route('industry'));
});`

In my views/industry/index.blade.php:
`{!! Breadcrumbs::render('industry') !!}`

and in my routes.php
`Route::resource('industry','IndustryController');`

Did I miss something in the installation?

**Comment by davejamesmiller** [comment]
In `routes.php` you don't have a route named `home`.
