### ISSUE TITLE
Support for additional metadata on the breadcrumbs?

### ISSUE THREAD

**Issue by judgej** [davejamesmiller/laravel-breadcrumbs#119]
Not a specific problem, more a question.

Does this package support additional metadata for a crumb? A specific example is the ability to give some context to the crumb for use with a hover-over (`title` attribute). A crumb trail like this provides no context:

~~~text
Home > Foo > Bar > Fred
~~~

What is Foo and Bar? No idea. Would be nice to hover the mouse over to find out that "Foo" is a company and "Bar" is a department.

Of course, a crumb-trail like this would help, but it can start to get very unwieldy as the levels grow, especially if Foo and Bar are long company and department names:

~~~text
Home > Companies > Foo > Departments > Bar > Employees > Fred
~~~

Just wondering if there is support out-of-the-box for additional metadata to help build up the crumbtrails.

**Comment by judgej** [comment]
If I could mark some crumbs as index/listing pages and some as specific entities, then it would be possible to build up the long form of the crumbrail as shown above, and collapse it into a neater form on rendering. It's all about giving the user context to where they are (as a constant reminder), but not trying to give them URLs to any possible page they use to get to that point, as that can lead to information overload.

**Comment by judgej** [comment]
Found the answer here:

http://laravel-breadcrumbs.davejamesmiller.com/en/latest/advanced.html#custom-data

Thanks :-)

**Comment by judgej** [comment]
Just to complete this, here is what I did. First I over-rode the rendering template (see `config/breadcrumbs.php`):

~~~php
@if ($breadcrumbs)
    <ol class="breadcrumb">
        @foreach ($breadcrumbs as $breadcrumb)
            @if ($breadcrumb->url && !$breadcrumb->last)
                <li><a href="{{{ $breadcrumb->url }}}" title="{{ isset($breadcrumb->context) ? $breadcrumb->context : '' }}">{{{ $breadcrumb->title }}}</a></li>
            @else
                <li title="{{ isset($breadcrumb->context) ? $breadcrumb->context : '' }}" class="active">{{{ $breadcrumb->title }}}</li>
            @endif
        @endforeach
    </ol>
@endif
~~~

Then anywhere that a breadcrumb is pushed, I do it like this:

~~~php
$breadcrumbs->push($show->name, route('my.route.name', ...), ['context' => 'What this crumb represents text']);
~~~

That then provides the specified "context" text as the title attribute on the crumbtrail links or non-link text.

That's it. Simple.

**Comment by davejamesmiller** [comment]
:+1: 

FYI you can shorten this:

```
title="{{ isset($breadcrumb->context) ? $breadcrumb->context : '' }}"
```

To this:

```
title="{{ $breadcrumb->context or '' }}"
```

https://laravel.com/docs/5.2/blade#displaying-data

**Comment by judgej** [comment]
I'm going to have to go back to PHP school :-)

This works:

    {{ $breadcrumb->context or '' }}

This gives an error for breakcrumbs where the contact property does not exist:

    {{ $breadcrumb->context }}

How does that `or` do that?

**Comment by judgej** [comment]
Phew - I'm not going mad:

https://laravel-news.com/2014/07/blade-or-operator/

Lovely feature - thank you for introducing it to me.
