### ISSUE TITLE
sending additional data to register method of laravel-breadcrumbs

### ISSUE THREAD

**Issue by ahmadbadpey** [davejamesmiller/laravel-breadcrumbs#120]
To create breadcrumbs for my App, I am using davejamesmiller/laravel-breadcrumbs laravel package. that is easy and great But I have a problem with it.

Suppose I have a default blade template like this :

```
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        @if (isset($pageTitle))
            - {{$pageTitle}}
        @endif
    </title>
</head>
<body>
<div class="wrapper">
    {!! Breadcrumbs::render(Request::route()->getName(),$pageTitle) !!}

    <section class="content">
        @yield('content')
    </section>
</div>
</body>
</html>
```
And other blade templates extends it like this (for example admin.course.index):

```
@extends('admin.default',['pageTitle'=>'All Courses'])

@section('content')
    <div class="row">
        <div class="col-xs-12">
        </div>
    </div>
@endsection

```
And in the Routes.php , I have a resource named course :
```
Route::group(
            array (
                'prefix' => 'admin'
            ),
            function () {
                Route::resource('course', 'CourseController');
            }
);
```
Now I want to use same $pageTitle variable defined in child blade template and shown as breadcrumbs title.

Also in the _app/Http/breadcrumbs.php_ , there are these :

```
Breadcrumbs::register('admin', function ($breadcrumbs) {
        $breadcrumbs->push('Management', route('desktop'));
    });

Breadcrumbs::register('admin.course.index', function ($breadcrumbs, $pageTitle) {
    $breadcrumbs->parent('admin');
    $breadcrumbs->push($pageTitle, route('admin.course.index'));
});

Breadcrumbs::register('admin.course.create', function ($breadcrumbs, $pageTitle) {
    $breadcrumbs->parent('admin.course.index');
    $breadcrumbs->push($pageTitle, route('admin.course.create'));
});

```
In admin.course.index Breadcrumbs register method , I send _$pageTitle_ as second Argument and all things work fine.

But when opening admin.course.create blade template , below error occured :

```
ErrorException in breadcrumbs.php line 20:
Undefined variable: pageTitle (View: D:\wamp\www\lms\resources\views\admin\default.blade.php) (View: D:\wamp\www\lms\resources\views\admin\default.blade.php)
```
Because in the _$breadcrumbs->parent('admin.course.index');_ part of _Breadcrumbs::register('admin.course.create')_ I must send a parameter again to breadcrumbs ,while in this case I do not What should I send??

Who solution to this problem?

**Comment by davejamesmiller** [comment]
As you seem to have worked out, the problem is you're defining the function with a required parameter:

```php
Breadcrumbs::register('admin.course.index', function ($breadcrumbs, $pageTitle) {
    $breadcrumbs->parent('admin');
    $breadcrumbs->push($pageTitle, route('admin.course.index'));
});
```

Then calling it without any parameter:

```php
$breadcrumbs->parent('admin.course.index');
```

You ask:

> What should I send??

My question is: **What do you want it to do?**

One option is to specify the page title every time you call the function from a child page:

```php
$breadcrumbs->parent('admin.course.index', 'All Courses');
```

But that's a lot of unnecessary repetition. The way I'd do it is to remove the parameter entirely:

```php
Breadcrumbs::register('admin.course.index', function ($breadcrumbs) {
    $breadcrumbs->parent('admin');
    $breadcrumbs->push('All Courses', route('admin.course.index'));
});
```

```php
$breadcrumbs->parent('admin.course.index');
```

You can see this structure used in the examples in the documentation:
http://laravel-breadcrumbs.davejamesmiller.com/en/latest/defining.html#static-pages
