### ISSUE TITLE
Working with Route Groups

### ISSUE THREAD

**Issue by johnnycho** [davejamesmiller/laravel-breadcrumbs#121]
(For support requests / bug reports, please complete the following - or delete if not applicable.)

**Summary of issue**

Almost everything is working fine and I'm not getting error messages. There's just one thing that isn't working properly:

In addition to my regular routes, I've placed several routes within an "admin" route group, which executes auth middleware for authentication.

Outside of this route group, I use a slash ('/') to indicate the route for the public homepage (i.e. domain.com/).
INSIDE the route group, I use a slash ('/') to indicate the route for the dashboard of the admin site (i.e. domain.com/admin).

Laravel itself understands all this and everything works fine. But Laravel Breadcrumbs seems to be ignoring route groups and uses the last instance of the route ('/') in routes.php, which of course is located inside the "admin" route group.

So the breadcrumb for "Home" goes to the admin site homepage, not the public site homepage, which is the preferred route.

**The complete error message, including file & line numbers**

There is no error message. The breadcrumb merely displays the wrong URL for "Home."

**Steps to reproduce the problem**

1. Create a route for "/" in routes.php that executes a controller method that returns the public homepage view.

2. Create a route group called "admin" in routes.php.

3. Create a route inside the "admin" route group for "/" that executes a controller method that returns the admin dashboard view.

4. Add a breadcrumb for "/" (actually, I guess you would also need to create at least one child route for this route, so that "Home" displays as a link rather than as unlinked text).

**Versions**
Laravel Breadcrumbs 3.0.0
Laravel 5.1.35
PHP 5.5.31

**Copy of `app/Http/breadcrumbs.php`**
```php
<?php

// Home
Breadcrumbs::register('home', function($breadcrumbs)
{
    $breadcrumbs->push('Home', route('/'));
});

// Home > Services
Breadcrumbs::register('services', function($breadcrumbs)
{
    $breadcrumbs->parent('home');
    $breadcrumbs->push('Services', route('services'));
});
```

**Copy of `config/breadcrumbs.php` (if used)**
```php

```

**Copy of the view and/or layout files**

**Copy of the custom breadcrumbs template (if applicable)**
```php
{!! Breadcrumbs::render('services', $services) !!}
```
where $service is an object containing data on services rendered

This renders:
Home / Services
where Home is a link that goes to the admin dashboard, not the public homepage

**Copy of `config/app.php`**
```php

```

**Copy of any other relevant files**
```php

```

**Any other information**

**Comment by davejamesmiller** [comment]
You didn't include a copy of your routes file, but from the description it sounds like this:

```php
Route::get('/', 'HomeController@index');

Route::group(['prefix' => 'admin'], function() {
    Route::get('/', 'AdminController@index');
});
```

And I think you are expecting to be able to call `route('/')` and have it return `/admin`?

If so, that's not how Laravel works - the above is just a shorthand for:

```php
Route::get('/', 'HomeController@index');
Route::get('admin', 'AdminController@index');
```

So the correct method call would be `url('admin')`.

Or name your routes using `['as' => 'admin::']` on the group and `['as' => 'home']` on the action and use `route('admin::home')` (https://laravel.com/docs/5.2/routing#named-routes).

You will find it works the same if you put the function call straight into your view - Laravel Breadcrumbs is doing nothing special here.

If I misunderstood, please reply with a copy of your routes file, and also expand on "Laravel itself understands all this and everything works fine" - what exactly works fine? Can you call `route()` in a view and what does it return.

**Comment by johnnycho** [comment]
Attached is my routes.php file. You correctly guessed the relevant routes and route group (mine is called DashboardController instead of AdminController but the structure is the same). But what I'm expecting is the opposite of what you described. I'm expecting to be able to call route('/') and have it go to 'domain.com/' not 'domain.com/admin'

What I meant by "Laravel itself understands all this and everything works fine" (sorry for the vagueness) is that when I go to 'domain.com/' it returns the HomeController@index and when I go to 'domain.com/admin' it returns the DashboardController@index.
[routes.php.zip](https://github.com/davejamesmiller/laravel-breadcrumbs/files/262043/routes.php.zip)

**Comment by davejamesmiller** [comment]
OK, I see.

The problem is you have specifically told it that `route('/')` should return `/admin` by putting `'as' => '/'` in this line:

```php
Route::group(array('prefix' => 'admin'), function()
{
	Route::group(['middleware' => 'auth'], function()
	{
		Route::get('/', array('as' => '/', 'uses' => 'Admin\DashboardController@index'));
	});
});
```

Removing the groups, this is equivalent to:

```php
Route::get('admin', ['as' => '/', 'uses' => 'Admin\DashboardController@index', 'middleware' => 'auth']);
```

So you can either use `url('/')` instead of `route('/')`, or change this:

```php

Either way it's not a Breadcrumbs issue and you will have the same problem if you put a link anywhere in your view.

**Comment by johnnycho** [comment]
Got it. Thanks. Changing it to `url('/')` instead of `route('/')` works and is probably the best solution. And I see now where that's explained in the documentation, under Defining Breadcrumbs > Static Pages.

**Comment by davejamesmiller** [comment]
:smiley:
