### ISSUE TITLE
Throw exception if accidentally called recursively

### ISSUE THREAD

**Issue by alexglue** [davejamesmiller/laravel-breadcrumbs#123]
(For support requests / bug reports, please complete the following - or delete if not applicable.)

**Summary of issue**
Uncatched fall into infinite crumbs loading. 

**The complete error message, including file & line numbers**
Now we fall into infinite crumbs loading due to crumb parent points to itself;

**Software versions**
Laravel Breadcrumbs: 
last version
Laravel: 5.2
PHP: 7.0.5

**Copy of `app/Http/breadcrumbs.php`**
```php
        Breadcrumbs::register(
            'admin.users.show', function ( Generator $breadcrumbs ) {
            $breadcrumbs->parent( 'admin.users.show' );
            $breadcrumbs->push( trans( 'admin.models.user.actions.show' ), route( 'admin.users.show' ), [ 'icon' => 'fa-eye' ] );
        }
        );
```

**Comment by davejamesmiller** [comment]
Potentially possible, but limiting recursive function calls is already handled by Xdebug so it's not a high priority.

https://xdebug.org/docs/all#max_nesting_level

I'd accept a pull request, but I'm not likely to spend time writing it myself.

**Comment by davejamesmiller** [comment]
**Laravel Breadcrumbs is no longer officially maintained**
Please [see the README file](https://github.com/davejamesmiller/laravel-breadcrumbs/blob/master/README.rst) for further details.
