### ISSUE TITLE
Last item to link

### ISSUE THREAD

**Issue by raindy29** [davejamesmiller/laravel-breadcrumbs#125]
For support requests 

how to make last item link
thanks

[home](url) > [item1](url) >  [item2](url)  > item3

**The complete error message, including file & line numbers**

**Software versions**
Laravel Breadcrumbs: 3
Laravel: 5.2
PHP: 7

**Copy of `app/Http/breadcrumbs.php`**
Breadcrumbs::register('productlist', function($breadcrumbs,$category)
{
    $breadcrumbs->parent('home');
    foreach ($category as $key=>$ary){
       $breadcrumbs->push($ary['title'], route('productlist',$ary['id'])   );
    }
});

View
{!! Breadcrumbs::render('productlist',$Upper->tree ) !!}

**Comment by davejamesmiller** [comment]
Create a custom template and remove the `@if (!$breadcrumb->last)` check.

http://laravel-breadcrumbs.davejamesmiller.com/en/latest/templates.html
