### ISSUE TITLE
Dependency injection

### ISSUE THREAD

**Issue by Malezha** [davejamesmiller/laravel-breadcrumbs#126]
I would like able to control not only using facade, but also having the interface to injection in methods.

**Comment by davejamesmiller** [comment]
**Laravel Breadcrumbs is no longer officially maintained**
Please [see the README file](https://github.com/davejamesmiller/laravel-breadcrumbs/blob/master/README.rst) for further details.

**Comment by davejamesmiller** [comment]
I’ve decided to [start working on Laravel Breadcrumbs again](https://davejamesmiller.com/2017/06/24/laravel-breadcrumbs-redux).

This will be [added in v4](https://github.com/davejamesmiller/laravel-breadcrumbs/pull/140).
