### ISSUE TITLE
Hide/Not Show breadcrumbs on specific pages, using Route-Bound Breadcrumbs

### ISSUE THREAD

**Issue by mstnorris** [davejamesmiller/laravel-breadcrumbs#127]
I'm using the [Route-Bound Breadcrumbs](http://laravel-breadcrumbs.davejamesmiller.com/en/latest/routing.html#route-bound-breadcrumbs) approach and would like to know how to _hide_ or _not show_ breadcrumbs on specific pages. For example, I don't think it is necessary on the login or register pages.

I have found the `renderIfExists()` method and that _does_ work, but I wasn't sure if that was the right way to go about it?

**Software versions**
Laravel Breadcrumbs: latest
Laravel: 5.2
PHP: 7.0.8-2

**Comment by davejamesmiller** [comment]
Yes, I think that will work fine.

**Comment by mstnorris** [comment]
I wasn't sure if that would leave residual code but it appears not, so yeah, I think it works too! Thanks.

Maybe you could mention that in the docs as I'm sure Im not the only one who wants breadcrumbs, but not on all pages.

Thanks again for this great little package.

**Comment by mstnorris** [comment]
Ahh, just tried to remove the breadcrumb on the homepage, but show it on subsequent pages that require it, and it of course crashes. Is there anyway around this?

**Comment by davejamesmiller** [comment]
> Maybe you could mention that in the docs as I'm sure Im not the only one who wants breadcrumbs, but not on all pages.

It is mentioned on both the [Route-Bound Breadcrumbs](http://laravel-breadcrumbs.davejamesmiller.com/en/latest/routing.html#output-breadcrumbs-in-your-layout) page you linked above and in [Advanced](http://laravel-breadcrumbs.davejamesmiller.com/en/latest/advanced.html#checking-if-a-breadcrumb-exists).

If you have a suggestion for improved wording or anywhere else it should be mentioned please do submit a PR (just click the Edit on GitHub button) or let me know.

> Ahh, just tried to remove the breadcrumb on the homepage, but show it on subsequent pages that require it, and it of course crashes. Is there anyway around this?

Yes, just give it a different name. e.g. If your home route is called `home`, call it `homepage`.

**Comment by mstnorris** [comment]
Thank you, I'll have a look at the wording and edit accordingly. As for not showing it on certain pages, the trick you mentioned above about using a different name within the `app/Http/breadcrumbs.php` file worked! Thanks.
