### ISSUE TITLE
Route::resource show() parameter is not equivalent register($breadcrumbs,$parameter)

### ISSUE THREAD

**Issue by phper01** [davejamesmiller/laravel-breadcrumbs#135]
1.When i using Route::resource('project') in route.php ,this function show($id) and this parameter is a id, a number.But the Docs :

```
// Photos > [Photo Name]
Breadcrumbs::register('photo.show', function($breadcrumbs, $photo)
{
    $breadcrumbs->parent('photo.index');
    $breadcrumbs->push($photo->title, route('photo.show', $photo->id));
});
``` 

this parameter $photo is a object,not a number ，
this my code:

```
Breadcrumbs::register('admin.project.show', function($breadcrumbs,$data)
{
    dd($data);
    $breadcrumbs->parent('admin.project.index');
    $breadcrumbs->push($project->title, route('admin.project.show',$project->id));
});
```

show a number .$project->title is not hava.
How i can do it.thanks

**Comment by davejamesmiller** [comment]
It will receive the same parameters as the action.

https://laravel.com/docs/5.3/routing#route-model-binding

**Comment by phper01** [comment]
thanks so much ,it's solved
