### ISSUE TITLE
Missing argument 2 on dynamic breadcrumbs

### ISSUE THREAD

**Issue by tutNichts** [davejamesmiller/laravel-breadcrumbs#136]
(For support requests / bug reports, please complete the following - or delete if not applicable.)

**Summary of issue**
I just extended your Manager class, to be able to support Structured Data (for Google Breadcrumbs). Works fine, but not with dynamic parameters. Any idea?

**The complete error message, including file & line numbers**
ErrorException in breadcrumbs.php line 19:
Missing argument 2 for App\Providers\BreadcrumbExtensionProvider::{closure}() (View: /Applications/MAMP/htdocs/newcomer-des-raps/resources/views/layouts/app.blade.php) (View: /Applications/MAMP/htdocs/newcomer-des-raps/resources/views/layouts/app.blade.php)

**Software versions**
Laravel Breadcrumbs: 
Laravel: 5.3
PHP: 7

**Copy of `routes/breadcrumbs.php` (or `app/Http/breadcrumbs.php`)**
```php
Breadcrumbs::register('charts.index', function($breadcrumbs) {
    $breadcrumbs->push('Startseite', url('/'));
    $breadcrumbs->push('Charts', route('charts.index'));
});

Breadcrumbs::register('charts.release-type', function($breadcrumbs, $releaseType) {
    $breadcrumbs->parent('charts.index');
    $breadcrumbs->push($releaseType->name, route('charts.release-type', [$releaseType->slug]));
});

Breadcrumbs::register('charts.week', function($breadcrumbs, $releaseType, $chartWeek) {
    $breadcrumbs->parent('charts.release-type', $releaseType);
    $breadcrumbs->push($chartWeek->name, route('charts.week', [$releaseType->slug, $chartWeek->slug]));
});
```

**Copy of `routes/web.php` (or `app/Http/routes.php`)**
```php
Route::group(['prefix'=>'charts'], function() {
    Route::group(['prefix'=>'{releaseType}'], function() {
        Route::get('{week}', 'ChartController@week')->name('charts.week');
        Route::get('/', 'ChartController@releaseType')->name('charts.release-type');
    });
    Route::get('/', 'ChartController@index')->name('charts.index');
});
```

**Copy of `config/breadcrumbs.php` (if used)**
```php
not necessary
```

**Copy of the view and/or layout files (e.g. `resources/views/home.blade.php`, `resources/views/layouts/master.blade.php`)**
```php
@section('breadcrumbs')
    {!! Breadcrumbs::renderIfExists('charts.release-type', $releaseType) !!}
@stop
```

**Copy of the custom breadcrumbs template (if used, e.g. `resources/views/_partials/breadcrumbs.blade.php`)**
```php
not necessary
```

**Copy of `config/app.php`**
```php
not necessary
```

**Copy of any other relevant files**
```php
not necessary
```

**Any other information**

**Comment by davejamesmiller** [comment]
> I just extended your Manager class, to be able to support Structured Data (for Google Breadcrumbs). Works fine, but not with dynamic parameters. Any idea?

It would be helpful to include a copy of that code then, no?

But you don't really need to extend anything - just create a custom template.

**Comment by tutNichts** [comment]
```php
<?php
namespace App\Helpers;
use DaveJamesMiller\Breadcrumbs\Manager;

/**
 * Created by PhpStorm.
 * User: vincentpetritz
 * Date: 02.10.16
 * Time: 18:10
 */

class BreadcrumbExtension extends Manager {

    public function getJsonLd($name) {
        if(!$this->exists($name)) {
            return null;
        }

        $result = [
            '@context'=>"http://schema.org",
            "@type"=>"BreadcrumbList"
        ];

        $counter = 1;
        foreach($this->generateIfExists($name) AS $item) {
            $result['itemListElement'][] = [
                "@type"=>"ListItem",
                "position"=>$counter++,
                "item"=>[
                    "@id"=>$item->url,
                    "name"=>$item->title
                ]
            ];
        }

        return json_encode($result, JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT);
    }
}
```

How should this custom template look like?

**Comment by davejamesmiller** [comment]
Earlier you said you were using this code to render it:

```php
{!! Breadcrumbs::renderIfExists('charts.release-type', $releaseType) !!}
```

But your method is defined like this:

```php
public function getJsonLd($name)
```

So I assume you're calling it something like this:

```php
{!! Breadcrumbs::getJsonLd('charts.release-type') !!}
```

It doesn't accept a second parameter, and it doesn't pass any second parameter to `generateIfExists()`. That's why you get the error "`Missing argument 2`".

> How should this custom template look like?

I was thinking something like this, with the HTML format rather than JSON.

https://github.com/davejamesmiller/laravel-breadcrumbs/pull/124/files#diff-d7801d103f2eb713c471b7b087266297

But even when generating pure JSON, I'd probably put it into a PHP view rather into the Manager class.

**Comment by tutNichts** [comment]
Ahh! Thanks for this! But the real problem I have is the same as here: http://laravel.io/forum/03-18-2014-blade-loads-overridden-views?page=1#reply-30263 - so I overwrite a section, but it's also executing the parent section, where I use a default method. Just my mistake. Sorry about that!
