### ISSUE TITLE
THIS PACKAGE IS NO LONGER MAINTAINED

### ISSUE THREAD

**Issue by davejamesmiller** [davejamesmiller/laravel-breadcrumbs#137]
**Laravel Breadcrumbs is no longer officially maintained**
Please [see the README file](https://github.com/davejamesmiller/laravel-breadcrumbs/blob/master/README.rst) for further details.

---

Feel free to use this issue to discuss possible forks among yourselves, but I please be aware I will not receive any notifications.

**Comment by maddhatter** [comment]
I don't have any desire to take over maintenance of this project, but I've added Laravel 5.4 support on my fork: https://github.com/maddhatter/laravel-breadcrumbs/tree/laravel-5.4

I'm only maintaining that fork for my personal projects, but figured I'd mention it here in case anyone else comes looking for Laravel 5.4 support with it dropping this week.

**Comment by MadMikeyB** [comment]
@davejamesmiller Just wanted to drop a thanks for maintaining this package for so long. 👍

**Comment by davejamesmiller** [comment]
@MadMikeyB Thanks 😃

**Comment by davejamesmiller** [comment]
@maddhatter Thanks for sharing. I've added 5.4 support in 3.0.2 (merged PR #139).

(Still not officially maintaining it, but I needed it for a project.)

**Comment by shigg1120** [comment]
Yea Thanks @davejamesmiller  I am using this package for my live website, and it works great

**Comment by decadence** [comment]
Maybe @freekmurze could take control of this package or make his alternative because @spatie has many great Laravel packages.

**Comment by freekmurze** [comment]
Thanks for kind words on our open source work, but currently we don't have a need for a breadcrumbs package.

**Comment by decadence** [comment]
Ok, I just asked.

**Comment by davejamesmiller** [comment]
I’ve decided to start working on Laravel Breadcrumbs again. Thanks to the people who took the time to contact me to say thanks - it really helped to motivate me to pick it up again. (More info [on my blog](https://davejamesmiller.com/2017/06/24/laravel-breadcrumbs-redux).)

**Comment by decadence** [comment]
Awesome news! Thanks for bringing it back and your work. Laravel community needs this package.

**Comment by decadence** [comment]
I bet first PR will be Laravel 5.5 auto-discovery support :)

**Comment by davejamesmiller** [comment]
@decadence Done in 4.x-dev :-)

**Comment by forxer** [comment]
Thank you very much, I use your package from the very beginning that I use Laravel, it is simply essential.

**Comment by ceesco53** [comment]
Just another thanks here for all the hard work.
