### ISSUE TITLE
how difficult would it be to use this for drop-down breadcrumbs?

### ISSUE THREAD

**Issue by vesper8** [davejamesmiller/laravel-breadcrumbs#149]
i'm making a football sports statistics site and i have data for many seasons, many leagues and many categories

I want a Breadcrumbs style navigation, meaning it'll look just like regular breadcrumbs but they'll be clickable and when clicked it would expand into a dropdown select

For example the landing page might be

Home > 2017-2018 -> Bantam BB -> Toronto South Shore -> Rankings

Then you could click on any of those 5 and have more options

Clicking on Rankings would show you a selection of say Rankings, Schedule, Contact

Clicking on 2017-2018 would let you pick an earlier year

And so on for each of them. Of course upon changing any of them the ones "below" would also change. I would need to handle that in the front-end.. kind of like good ole ajax chained select b oxes

But my question is does your package have something in it already that would allow me to structure something like this or would I be fighting against the way you did things and better off to start something fully custom ?

Would love your thoughts. thanks!

**Comment by davejamesmiller** [comment]
You can use the `$data` parameter to add any extra data you need to pass to a custom template.

e.g. `['menu' => 'years']` to specify one of several menus, or `['menu' => new YearsMenu]` if you want it object-oriented, or you could just pass an array of all the menu items like `['menu' => ['2017-2018' => route('...'), ...]]`.

https://github.com/davejamesmiller/laravel-breadcrumbs#custom-data
