### ISSUE TITLE
Usage in Blade Template

### ISSUE THREAD

**Issue by raphaelbeckmann** [davejamesmiller/laravel-breadcrumbs#150]
```@section('breadcrumbs', Breadcrumbs::render('home'))```

does not work any more with Laravel 5.4

Now you need to use

```
@section('breadcrumbs')
  {!! Breadcrumbs::render('home') !!}
@stop
```

which is a hardcore pain to change in 100+ views.

**Comment by davejamesmiller** [comment]
Already fixed in 4.x (requires Laravel 5.5).

**Comment by davejamesmiller** [comment]
FYI In case you want to backport it instead of upgrading:

https://github.com/davejamesmiller/laravel-breadcrumbs/commit/4ae5633feda512014ce35ebfc5da28644248486a
https://github.com/davejamesmiller/laravel-breadcrumbs#contributing
