### ISSUE TITLE
give a clear explanation of what is a breadcrumb and what it is for

### ISSUE THREAD

**Issue by lmj0011** [davejamesmiller/laravel-breadcrumbs#152]
It seems like the first section of the README.md should give a clear explanation of what is a breadcrumb and what it is for.

The README.md just dive into setting up breadcrumbs without saying why you should be using them.

ref: https://www.smashingmagazine.com/2009/03/breadcrumbs-in-web-design-examples-and-best-practices/

**Comment by davejamesmiller** [comment]
Well, if you're looking for a breadcrumbs package I assume you know what they are - it's a pretty well known term - but if you think you can write a clear explanation please do submit a PR.
