### ISSUE TITLE
Class 'DaveJamesMiller\Breadcrumbs\ServiceProvider' not found

### ISSUE THREAD

**Issue by nripendrasingh94** [davejamesmiller/laravel-breadcrumbs#155]
Sir, I have a little concern about Breadcrumbs.  I am using bellow configuration for my project but getting some error. 
Laravel Version: 5.5
PHP Version: 7.0.10
composer.json
"require": {
        "php": ">=7.0.0",
        "davejamesmiller/laravel-breadcrumbs": "4.x",
        "fideloper/proxy": "~3.3",
        "laravel/framework": "5.5.*",
        "laravel/tinker": "~1.0"
    },
    "require-dev": {
        "filp/whoops": "~2.0",
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~6.0"
    },

To embed your plugin I followed this steps.
Step 1: **composer require davejamesmiller/laravel-breadcrumbs**
(Installed successfully)
![1](https://user-images.githubusercontent.com/33955415/33207915-93f0aea0-d135-11e7-9921-d276d2a8af9b.PNG)
Step 2: Created a file called routes/breadcrumbs.php
<?php
Breadcrumbs::register('home', function ($breadcrumbs) {
    $breadcrumbs->push('Home', route('home'));
});
Step 3: config/app.php
'providers' => [
                ......
                DaveJamesMiller\Breadcrumbs\ServiceProvider::class,
],
'aliases' => [
                .....
		'Breadcrumbs' => DaveJamesMiller\Breadcrumbs\Facade::class,
 ],
After add this line to providers array:  DaveJamesMiller\Breadcrumbs\ServiceProvider::class, encounter an  error called::
![2](https://user-images.githubusercontent.com/33955415/33208166-868e6378-d136-11e7-8226-964b55be1129.png)
.
Thanks in advance.

**Comment by davejamesmiller** [comment]
> After add this line to providers array: DaveJamesMiller\Breadcrumbs\ServiceProvider::class

`DaveJamesMiller\Breadcrumbs\ServiceProvider` doesn't exist in 4.x.

If you have upgraded, follow the [upgrade instructions](https://github.com/davejamesmiller/laravel-breadcrumbs#upgrading-from-3x-to-4x)

If you are installing from scratch, make sure you're following the instructions for v4 not v3.

**Comment by nripendrasingh94** [comment]
Sir,
Thankyou for your help, Still I have problem.
I removed **DaveJamesMiller\Breadcrumbs\ServiceProvider and Facade from config/app.php**, but getting a new error called: 
![2-min](https://user-images.githubusercontent.com/33955415/33232401-c0ed08b2-d22b-11e7-90a1-d5a6e3b23b20.png)

This is my **laravel-breadcrumbs/config/breadcrumbs.php** code
![capture-min](https://user-images.githubusercontent.com/33955415/33232439-5a503524-d22c-11e7-8a51-9cf956e4d6fd.png)

**Comment by nripendrasingh94** [comment]
Sir, I'm very thankful to you. After so many time I got resolved this problem.
After removing DaveJamesMiller\Breadcrumbs\ServiceProvider this and Facade from config/app.php I received one new error, called
**Arguments
"Route [home] not defined. (View: C:\wamp\www\lv5\resources\views\home.blade.php)"**

I added this route
Route::get('/home', ['as'=>'home', function () {
    return view('home');
}]);

Instead This
Route::get('/home',  function () {
    return view('home');
});
---->And finaly I got resloved.
Thank you very much.
