### ISSUE TITLE
Default value for Exception in config/breadcrumbs.php

### ISSUE THREAD

**Issue by tatarysh** [davejamesmiller/laravel-breadcrumbs#157]
https://github.com/davejamesmiller/laravel-breadcrumbs/blob/860e8cb09977749f316d2225c6920daeef562f95/config/breadcrumbs.php#L46

I think you can set the default values form:
`env ('APP_DEBUG', false)`

**Comment by davejamesmiller** [comment]
You can do that in your app if you want to, but I won't change the default. If that exception happens in production, you obviously didn't test well enough in development.
