### ISSUE TITLE
breadcrumbs.php path does not update when uploaded to live server.

### ISSUE THREAD

**Issue by rhonz10** [davejamesmiller/laravel-breadcrumbs#159]
I have a Laravel 5.5 project with breadcrumbs and it works great on Homestead but breaks when uploaded to live server. 

`DaveJamesMiller\Breadcrumbs\BreadcrumbsServiceProvider::registerBreadcrumbs(): Failed opening required '/home/vagrant/Code/sweldomo_v2/routes/breadcrumbs.php' (include_path='.:/usr/lib/php:/usr/local/lib/php') 
`

It still looks for the routes/breadcrumbs.php from the old path on dev server when uploaded to the live server.

`composer dump-autoload` also spits the same error. Uninstall & reinstall did not work.

**Comment by davejamesmiller** [comment]
Works for me. Check your config file.

**Comment by rhonz10** [comment]
/*
    |--------------------------------------------------------------------------
    | Breadcrumbs File(s)
    |--------------------------------------------------------------------------
    |
    | The file(s) where breadcrumbs are defined. e.g.
    |
    | - base_path('routes/breadcrumbs.php')
    | - glob(base_path('breadcrumbs/*.php'))
    |
    */

    'files' => base_path('routes/breadcrumbs.php'),

    /*

**Comment by davejamesmiller** [comment]
Did you run config:cache on dev then copy it to live perhaps?

**Comment by davejamesmiller** [comment]
Yeah that's what I'm saying you shouldn't do. It will cache the development
config not the live.

**Comment by rhonz10** [comment]
dang it! it was the cached configs..

**Comment by narenemoji** [comment]
In BreadcrumbsServiceProvider.php line 92:

  DaveJamesMiller\Breadcrumbs\BreadcrumbsServiceProvider::registerBreadcrumbs(): Failed opening required '/var/www/ht
  ml/milesforce/routes/breadcrumbs.php' (include_path='.;C:\php\pear')


Script @php artisan ide-helper:generate handling the post-autoload-dump event returned with error code 255

**Comment by narenemoji** [comment]
what should i do ...please
