### ISSUE TITLE
Having trouble with Model Bind

### ISSUE THREAD

**Issue by CesarScur** [davejamesmiller/laravel-breadcrumbs#163]
I'll try to be brief, but if you need more data just ask =D
This is my controller/action signature:
```
    public function edit(Request $request, Vertical $vertical, UserMacro $macro)
```
And this is my BC for the corresponding route:
```
Breadcrumbs::register('macro-edit', function (Generator $breadcrumbs, $vertical, $macro) {
    $breadcrumbs->parent('macro-index');
    $breadcrumbs->push($macro->name, route('macro-edit', [$vertical->_id, $macro]));
});
```
I'm getting the string ID on $vertical and $macro, breaking on $macro->name. If I add Hints as the action have I get a`Type error`.
```
Trying to get property of non-object (View: /.../resources/views/layouts/app.blade.php) (View: /.../resources/views/layouts/app.blade.php)
```
```
Type error: Argument 2 passed to DaveJamesMiller\Breadcrumbs\BreadcrumbsServiceProvider::{closure}() must be an instance of App\Vertical, string given, called in /.../vendor/davejamesmiller/laravel-breadcrumbs/src/BreadcrumbsGenerator.php on line 68 (View: /.../resources/views/layouts/app.blade.php) (View: /.../resources/views/layouts/app.blade.php)
```

**Comment by davejamesmiller** [comment]
https://github.com/davejamesmiller/laravel-breadcrumbs#technical-support

**Comment by CesarScur** [comment]
https://stackoverflow.com/questions/48543700/having-trouble-with-model-bind-laravel-breadcrumbs
https://laravel.io/forum/having-trouble-with-model-bind-laravel-breadcrumbs
https://laracasts.com/discuss/channels/laravel/having-trouble-with-model-bind-laravel-breadcrumbs
How long I got to wait  till reopen this after not having answer? What if this is a bug?

**Comment by davejamesmiller** [comment]
> What if this is a bug?

If you're sure it's a bug then give me a reproducible bug report - or preferably fix it and open a PR. From what you said so far I think it's more likely something wrong in your code, but there's not enough information there to tell.

**Comment by CesarScur** [comment]
Why here is been used `parameters()` that return no model
https://github.com/davejamesmiller/laravel-breadcrumbs/blob/5076f9412f13bf4ccb4403604de8c6d680432b96/src/BreadcrumbsManager.php#L270

while over laravel side of things is used somethings along the lines of:

        $reflection = new \ReflectionMethod(
            $route->controller,
            Str::parseCallback($route->action['uses'])[1]
        );

        $params = $route->resolveMethodDependencies(
            array_values($route->parameters()), $reflection
        );

?

**Comment by davejamesmiller** [comment]
Laravel already replaces the parameters with the models, so `$route->parameters()` does return the models.

https://github.com/laravel/framework/blob/56a58e0fa3d845bb992d7c64ac9bb6d0c24b745a/src/Illuminate/Routing/ImplicitRouteBinding.php#L39
https://github.com/davejamesmiller/laravel-breadcrumbs/blob/master/tests/RouteBoundTest.php#L269-L277
