### ISSUE TITLE
Edit Breadcrumb Issue

### ISSUE THREAD

**Issue by mayank6199** [davejamesmiller/laravel-breadcrumbs#164]
@davejamesmiller Please take a look at this issue
I am facing this issue while adding breadcrumb on edit page.

**Type error: Too few arguments to function DaveJamesMiller\Breadcrumbs\BreadcrumbsServiceProvider::{closure}(), 1**

**routes/breadcrumbs.php:**
Breadcrumbs::register('employee.edit', function ($breadcrumbs, $employee) {
    $breadcrumbs->parent('employee.index');
    $breadcrumbs->push('Edit Employee', route('employee.edit', $employee->id));
});

**in Blade template:**
{{ Breadcrumbs::render('employee.edit') }}

**Comment by davejamesmiller** [comment]
https://github.com/davejamesmiller/laravel-breadcrumbs#technical-support
