### ISSUE TITLE
Changing background color

### ISSUE THREAD

**Issue by marc98sjd** [davejamesmiller/laravel-breadcrumbs#168]
How can I change the background color of my breadcrumb? Dont know if I need to change a file or what... (currently using bootstrap4 default config).

Thankyou!
![captura de 2018-02-12 19-40-46](https://user-images.githubusercontent.com/32141427/36113319-b67a75d8-102c-11e8-8172-24668fced223.png)

**Comment by davejamesmiller** [comment]
It's just html and css, nothing to do with this package.
