### ISSUE TITLE
Could not install on Laravel 5.5

### ISSUE THREAD

**Issue by nanadjei2** [davejamesmiller/laravel-breadcrumbs#172]
I tried installing this package into laravel 5.5 but I get:

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for davejamesmiller/laravel-breadcrumbs ^5.0 -> satisfiable by davejamesmiller/laravel-breadcrumbs[5.0.0].
    - Conclusion: remove laravel/framework v5.5.22
    - Conclusion: don't install laravel/framework v5.5.22
    - davejamesmiller/laravel-breadcrumbs 5.0.0 requires illuminate/view 5.6.* -> satisfiable by illuminate/view[v5.6.0, v5.6.1, v5.6.2, v5.6.3, v5.6.4, v5.6.5].
    - don't install illuminate/view v5.6.0|don't install laravel/framework v5.5.22
    - don't install illuminate/view v5.6.1|don't install laravel/framework v5.5.22
    - don't install illuminate/view v5.6.2|don't install laravel/framework v5.5.22
    - don't install illuminate/view v5.6.3|don't install laravel/framework v5.5.22
    - don't install illuminate/view v5.6.4|don't install laravel/framework v5.5.22
    - don't install illuminate/view v5.6.5|don't install laravel/framework v5.5.22
    - Installation request for laravel/framework (locked at v5.5.22, required as 5.5.*) -> satisfiable by laravel/framework[v5.5.22].

Installation failed, reverting ./composer.json to its original content.`

**Comment by davejamesmiller** [comment]
You need to specify the version or Composer will try to install the latest (not compatible) version.

**Comment by tranquilodf** [comment]
Hi! im having the same problem. How can i solve? Can u put a example please?

**Comment by davejamesmiller** [comment]
I think it's composer require <name>@<version> but check the composer docs.

**Comment by dhildreth** [comment]
For convenience sake:
`composer require davejamesmiller/laravel-breadcrumbs:4.x`
