### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by ankit-fourtek** [davejamesmiller/laravel-breadcrumbs#173]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for davejamesmiller/laravel-breadcrumbs ^5.0 -> satisfiable by davejamesmiller/laravel-breadcrumbs[5.0.0].
    - Conclusion: remove laravel/framework v5.5.39
    - Conclusion: don't install laravel/framework v5.5.39
    - davejamesmiller/laravel-breadcrumbs 5.0.0 requires illuminate/view 5.6.* -> satisfiable by illuminate/view[v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.2, v5.6.3, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - don't install illuminate/view v5.6.0|don't install laravel/framework v5.5.39
    - don't install illuminate/view v5.6.1|don't install laravel/framework v5.5.39
    - don't install illuminate/view v5.6.10|don't install laravel/framework v5.5.39
    - don't install illuminate/view v5.6.11|don't install laravel/framework v5.5.39
    - don't install illuminate/view v5.6.2|don't install laravel/framework v5.5.39
    - don't install illuminate/view v5.6.3|don't install laravel/framework v5.5.39
    - don't install illuminate/view v5.6.4|don't install laravel/framework v5.5.39
    - don't install illuminate/view v5.6.5|don't install laravel/framework v5.5.39
    - don't install illuminate/view v5.6.6|don't install laravel/framework v5.5.39
    - don't install illuminate/view v5.6.7|don't install laravel/framework v5.5.39
    - don't install illuminate/view v5.6.8|don't install laravel/framework v5.5.39
    - don't install illuminate/view v5.6.9|don't install laravel/framework v5.5.39
    - Installation request for laravel/framework (locked at v5.5.39, required as 5.5.*) -> satisfiable by laravel/framework[v5.5.39].

Installation failed, reverting ./composer.json to its original content.

**Comment by davejamesmiller** [comment]
For Laravel 5.5 you need LB 4.x not 5.x

**Comment by dhildreth** [comment]
For convenience sake:
`composer require davejamesmiller/laravel-breadcrumbs:4.x`
