### ISSUE TITLE
After execute the publish command, the config file not appear

### ISSUE THREAD

**Issue by erotundo** [davejamesmiller/laravel-breadcrumbs#177]
Hi!

After install and run the publish command for Laravel 5.4.x i get the message "Publish complete" but in app.php file into config folder not appear the lines to register the Facade and ServiceProvider. The breadcrumbs configuration file not generated into config folder.

If i try to install manually the service provider i get the error in line 221 of Facade with the message Manager::for() it's undefined

Regards

ER

**Comment by davejamesmiller** [comment]
It sounds like you're trying to follow the instructions for Laravel Breadcrumbs 5.1.0, but you must have an older version installed because the last version that was compatible with Laravel 5.4 is Laravel Breadcrumbs 3.0.3.

https://github.com/davejamesmiller/laravel-breadcrumbs/tree/3.x
