### ISSUE TITLE
Generate breadcrumbs for tabbed content

### ISSUE THREAD

**Issue by xzhenghao** [davejamesmiller/laravel-breadcrumbs#181]
Very sorry that i need to post it here, can't seem to find anything online.

Can this package be used to generate breadcrumbs for tabbed content?

**Comment by davejamesmiller** [comment]
I don't know what you mean.

**Comment by xzhenghao** [comment]
If i have a tabbed content in a page, how do i change the breadcrumb based
on the changed tab?

**Comment by davejamesmiller** [comment]
You would have to write your own JavaScript I guess.

**Comment by justinmoh** [comment]
@xzhenghao usually __Tabs__ are rendered by client-side javascript, whereas `laravel-breadcrumbs` is a server-side breadcrumb package -- there's no interactivity between your front-end javascript and the pacakge.
