### ISSUE TITLE
Method for does not exist.

### ISSUE THREAD

**Issue by partho-63** [davejamesmiller/laravel-breadcrumbs#186]
I was trying to use breadcrump in my Laravel project when the following error occurred. What am I doing wrong? And how to solve it?

ERROR:
```
ErrorException (E_ERROR)
Method for does not exist. (View: C:\xampp\htdocs\appname\resources\views\welcome.blade.php)
```

code in --- routes\breadcrump.php
```
<?php

// Welcome
Breadcrumbs::for('welcome', function ($trail) {
    $trail->push('Welcome', route('welcome'));
});
```
route named welcome
```
Route::get('/', function () {
    return view('welcome');
})->name('welcome');
```
code in --- resources\views\welcome.blade.php
```
<div class="content">
	<div class="title m-b-md">
		Website
	</div>

	{{ Breadcrumbs::render('welcome') }}

</div>
```

**Comment by davejamesmiller** [comment]
No idea.

**Comment by partho-63** [comment]
Sorry, it was my fault. I was following documentation for version 5.x while I was using the version 4.x !
For others who are facing the same problem just use
```
// Welcome
Breadcrumbs::register('welcome', function ($trail) {
    $trail->push('Welcome', route('welcome'));
});
```
instead of
```
// Welcome
Breadcrumbs::for('welcome', function ($trail) {
    $trail->push('Welcome', route('welcome'));
});
```
Follow the documentation https://github.com/davejamesmiller/laravel-breadcrumbs/tree/4.x
