### ISSUE TITLE
can't get post category

### ISSUE THREAD

**Issue by ehsanmusavi** [davejamesmiller/laravel-breadcrumbs#188]
Hi,
I have some trouble to get post category in my breadcrumbs.
I defined breadcrumbs like this:

// Home
Breadcrumbs::for('home', function ($trail) {
    $trail->push('Home', route('home'));
});

// Home > [Category]
Breadcrumbs::for('category', function ($trail, $category) {
    $trail->parent('home');
    $trail->push($category->title, route('category', $category->slug));
});

// Home > [Category] > [Post]
Breadcrumbs::for('post', function ($trail, $post) {
    $trail->parent('category', $post->category);
    $trail->push($post->title, route('post', $post->slug));
});

and in my post view template:
{{ Breadcrumbs::render( 'post', $post ) }}

but getting this error on post view:
Undefined property: stdClass::$category

and this refers to this line of defined breadcrumb:
$trail->parent('category', $post->category);

my posts table does not have category column!
what should i pass as the second parameter of parent method? and should i pass post's category row to my post view?

**Comment by davejamesmiller** [comment]
Not a bug

**Comment by ehsanmusavi** [comment]
Where shouid I looking for support then?

**Comment by davejamesmiller** [comment]
Read the readme

**Comment by ehsanmusavi** [comment]
I read that and still I have this issue

**Comment by davejamesmiller** [comment]
Read the bit about technical support

**Comment by ehsanmusavi** [comment]
I asked on stackoverflow but no one answered!
I appreciate you for providing this package for free but I think you should have some support for someone who has some issues with it

**Comment by davejamesmiller** [comment]
https://medium.com/@DaveJamesMiller/laravel-breadcrumbs-redux-e91c2e90abc3

**Comment by ehsanmusavi** [comment]
Can you just tell me what should I pass as the second parameter of parent method for getting category?
$trail->parent('category', $post->category);
Is this category title column in posts table or what?

**Comment by davejamesmiller** [comment]
No. Why should I debug your code for you?

**Comment by ehsanmusavi** [comment]
I don't want you to debug my code! I jsut asking a simple damn question!

**Comment by ehsanmusavi** [comment]
I figured it out somehow. Thanks for your awesome support!
