### ISSUE TITLE
installed the package and got Class 'Breadcrumbs' not found error

### ISSUE THREAD

**Issue by GiacomoK** [davejamesmiller/laravel-breadcrumbs#194]
I installed the package with composer, I createad routes/breadcrumbs.php file, add some Breadcrumb and I got the error as subject.

Do I have to add something to my config/app.php file?

**Comment by davejamesmiller** [comment]
No, not in Laravel 5.5+.

**Comment by GiacomoK** [comment]
I tried to reinstall the package, same result :(
