### ISSUE TITLE
Feature Request UIKit breadcrumbs

### ISSUE THREAD

**Issue by PieterHollevoet** [davejamesmiller/laravel-breadcrumbs#196]
I would like to add the UiKit breadcrumbs to the package

**Comment by davejamesmiller** [comment]
Not sure why you immediately closed this but I'd accept a PR for it if you're still interested.

As well as adding the view file you would need to update the readme and comments in the config file.

If you could also make a PR for the [test app](https://github.com/davejamesmiller/laravel-breadcrumbs-test) at the same time that would help so I can test it, or at least send me the HTML needed to make a test page [like this](https://github.com/davejamesmiller/laravel-breadcrumbs-test/blob/master/laravel-5.7-project/resources/views/foundation6.blade.php).

Thanks

**Comment by davejamesmiller** [comment]
👍

**Comment by PieterHollevoet** [comment]
I made the pull requests

**Comment by davejamesmiller** [comment]
Thanks!

For reference:

- https://github.com/davejamesmiller/laravel-breadcrumbs/pull/198
- https://github.com/davejamesmiller/laravel-breadcrumbs-test/pull/1

**Comment by davejamesmiller** [comment]
Released in 5.2.0 - Thanks again!
