### ISSUE TITLE
Does this package even works???

### ISSUE THREAD

**Issue by UdyW** [davejamesmiller/laravel-breadcrumbs#197]
Does this package work for anyone? I'm getting error "Breadcrumb not found with name 'path-to-page'". I did everything instructed as the documentation, really simple. and it does not work. 
I have read other forums and got to know they also had the same issue.
So my question is had anyone got this to work?

**Comment by davejamesmiller** [comment]
Yes, it works...

**Comment by davejamesmiller** [comment]
If you can produce an actionable bug report of course. I can't do a thing with just the error message.
