### ISSUE TITLE
"Home" breadcrumb shows up twice, unable to remove it

### ISSUE THREAD

**Issue by aalaap** [davejamesmiller/laravel-breadcrumbs#199]
Here is my breadcrumb definition:

    Breadcrumbs::for('index', function ($trail) {
        $trail->push('Home', route('frontend.index'));
    });

    Breadcrumbs::for('frontend.content.news.index', function ($trail) {
        $trail->parent('index');
        $trail->push('News', route('frontend.content.news.index'));
    });

    Breadcrumbs::for('frontend.content.news.show', function ($trail, $news) {
        $trail->parent('frontend.content.news.index');
        $trail->push($news->title, route('frontend.content.news.show', $news->slug));
    });

This is how my breadcrumbs are shown:

1. Homepage:

    Home / Home

2. News index:

    Home / Home / News

3. News detail

    Home / Home / News / This is a news item

The last items in each trail are linked, as is expected. The first `Home` is always present and unlinked. I have no breadcrumb defined as `home`. The one named `index' is my `home`. There is no other code adding any other crumb to the trail. Where is the base home crumb coming from?

I have the same problem with the backend breadcrumbs. `Home` is always present and unlinked.

What am I getting confused with here?

**Comment by davejamesmiller** [comment]
No idea - looks right to me. Maybe it's in a different file somewhere, or if you have a custom template maybe accidentally hard-coded in there? But I can only guess.

**Comment by aalaap** [comment]
I found the problem: a home link was hard-coded in the view template before the loop!

**Comment by davejamesmiller** [comment]
👍
