### ISSUE TITLE
Implicit controllers usable

### ISSUE THREAD

**Issue by voodooattack** [davejamesmiller/laravel-breadcrumbs#64]
The documentation mentions that implicit controllers could not be used; but after a bit of hunting I've tested with Laravel 5.0.3, and it can be done by passing a third argument to Route::controller:

```
Route::controller('auth', 'Auth\AuthController', [
  'getRegister' => 'auth.register',
  'getLogin' => 'auth.login',
  'postRegister' => 'auth.register',
  'postLogin' => 'auth.login',
  'postLogout' => 'auth.logout',
]);
```

Just thought I'd leave this here for anybody interested in a solution.

**Comment by davejamesmiller** [comment]
Thanks for that. I'll add it next time I'm working on the docs - unless you or someone else wants to make a PR for it first.
