### ISSUE TITLE
Class 'DaveJamesMiller\Breadcrumbs\ServiceProvider' not found 

### ISSUE THREAD

**Issue by khalid11** [davejamesmiller/laravel-breadcrumbs#66]
Hi,

I am facing following error:

Class 'DaveJamesMiller\Breadcrumbs\ServiceProvider' not found 

Please help me, I follow complete instruction when installing.

I am installing package in Laravel 4.42 version.

Thanks in advance.

**Comment by davejamesmiller** [comment]
There is no Laravel 4.42 so I assume you mean 4.2?

Breadcrumbs 3 is only compatible with Laravel 5. Did you follow the instructions to install Breadcrumbs 2?

Is it installed correctly in the `vendor/davejamesmiller/laravel-breadcrumbs/` directory?

**Comment by khalid11** [comment]
Yes, I have Breadcrumb 2 invendor/davejamesmiller/laravel-breadcrumbs/
Directory also I follow all instructions.

**Comment by davejamesmiller** [comment]
Please provide the more detail as per https://github.com/davejamesmiller/laravel-breadcrumbs/blob/master/CONTRIBUTING.rst. Thanks

**Comment by khalid11** [comment]
I follow each step which is given here:

https://github.com/davejamesmiller/laravel-breadcrumbs/tree/2.x

Do you want me to share my code setting which I did?

**Comment by davejamesmiller** [comment]
Yes, I want you to read the link - particularly the bit which starts "All support requests / bug reports should include the following:".

**Comment by khalid11** [comment]
Here is the process which I follow in installation and setting:

1. I run following command to install:   composer require davejamesmiller/laravel-breadcrumbs:2.*

2. After successful installation I put below code in app/config/app.php:

    'providers' => array(
        // ...
        'DaveJamesMiller\Breadcrumbs\ServiceProvider',
    ),

And:

    'aliases' => array(
        // ...
        'Breadcrumbs' => 'DaveJamesMiller\Breadcrumbs\Facade',
    ),

3. Then I have create a file call breadcrums.php in my app folder and put below code in breadcrums.php file:

<?php

Breadcrumbs::register('home', function($breadcrumbs) {
    $breadcrumbs->push('Home', route('home'));
});

Breadcrumbs::register('blog', function($breadcrumbs) {
    $breadcrumbs->parent('home');
    $breadcrumbs->push('Blog', route('blog'));
});

Breadcrumbs::register('category', function($breadcrumbs, $category) {
    $breadcrumbs->parent('blog');

    foreach ($category->ancestors as $ancestor) {
        $breadcrumbs->push($ancestor->title, route('category', $ancestor->id));
    }

    $breadcrumbs->push($category->title, route('category', $category->id));
});

Breadcrumbs::register('page', function($breadcrumbs, $page) {
    $breadcrumbs->parent('category', $page->category);
    $breadcrumbs->push($page->title, route('page', $page->id));
});

4. Then I create a view file in following path:  app/views/_partials/breadcrumbs.blade.php and put below code:

@if ($breadcrumbs)
    <ul class="breadcrumb">
        @foreach ($breadcrumbs as $breadcrumb)
            @if (!$breadcrumb->last)
                <li><a href="{{{ $breadcrumb->url }}}">{{{ $breadcrumb->title }}}</a></li>
            @else
                <li class="active">{{{ $breadcrumb->title }}}</li>
            @endif
        @endforeach
    </ul>
@endif

5. Then I add below code in my config app.php file:

'view' => '_partials.breadcrumbs',

6. In final step I call Breadcrumb in my view file:

{{ Breadcrumbs::render('home') }}
{{ Breadcrumbs::render('category', $category) }}

But it give me Class 'DaveJamesMiller\Breadcrumbs\ServiceProvider' not found error.

Can you please guide me how I can fix the problem?

Thanks in advance.

**Comment by davejamesmiller** [comment]
I have added code blocks markers to your message to make it readable - please see here if you aren't familiar with Markdown: https://help.github.com/articles/github-flavored-markdown/

I assume you didn't add the following code literally, but added the service provider to the end of the existing array? Can you show the the actual code in full? Maybe just paste in the whole file (other than encryption key or other sensitive things?

```
    'providers' => array(
        // ...
        'DaveJamesMiller\Breadcrumbs\ServiceProvider',
    ),
```

Otherwise I can't see anything wrong.

Can you check what is in the file `vendor/composer/autoload_namespaces.php`? 

Please also run these commands and paste the output:

```
composer status
composer show -i
```

**Comment by willycamargo** [comment]
I had the same problem.
I run: "composer update" and the problem was solved.

**Comment by UjjavalMoradiya** [comment]
You need to comment the following line in config/app.php (and then uncomment once composer has done its thing).
`DaveJamesMiller\Breadcrumbs\ServiceProvider::class,`

I got to know about this solution from [here](https://github.com/davejamesmiller/laravel-breadcrumbs/issues/19) and worked for me also.
