### ISSUE TITLE
Undefined variable: breadcrumbs with custom view

### ISSUE THREAD

**Issue by almamundinajpuri** [davejamesmiller/laravel-breadcrumbs#69]
Hello,

I tried to create a view according to your doc (http://laravel-breadcrumbs.davejamesmiller.com/en/latest/templates.html)
Breadcrumb works fine with renderIfExists() method, but with custom view I get error.

Thanks in advance.

**Comment by davejamesmiller** [comment]
You've given me no information to even guess what's wrong...

https://github.com/davejamesmiller/laravel-breadcrumbs/blob/master/CONTRIBUTING.rst
