### ISSUE TITLE
Call to undefined method DaveJamesMiller\Breadcrumbs\Facade::render()

### ISSUE THREAD

**Issue by anhuibl** [davejamesmiller/laravel-breadcrumbs#71]
Hello,
I'm using laravel 4.2.
I have already followed 2 steps of installation, 3 steps of usage. But I still have this error:
    Call to undefined method DaveJamesMiller\Breadcrumbs\Facade::render()
Please help me!
Thank you.

**Comment by davejamesmiller** [comment]
I'm not sure what you expect me to do with so little information to go on...

https://github.com/davejamesmiller/laravel-breadcrumbs/blob/master/CONTRIBUTING.rst

**Comment by wdmtech** [comment]
Did you add the facade to your aliases?

```PHP
'aliases' => [
    // ...
    'Breadcrumbs' => 'DaveJamesMiller\Breadcrumbs\Facade',
],
```

**Comment by anhuibl** [comment]
Thanks Dave James Miller and wdmTech for supporting.
My environment information:
- Breadcrumbs version: 2 (.x - For laravel 4.x)
- Laravel version: 4.2
- PHP version: PHP 5.5.9-1ubuntu4.9 (cli) (built: Apr 17 2015 11:44:57) 
Here are what I did:
1. I installed via Composer by command:
$composer require davejamesmiller/laravel-breadcrumbs:2.*
then I update composer.

2. I added to app/config/app.php as instructions, 'DaveJamesMiller\Breadcrumbs\ServiceProvider' (provider) and 'Breadcrumbs' => 'DaveJamesMiller\Breadcrumbs\Facade' (aliases)

3. I created file  app/breadcrumbs.php with content like this:
<?php

Breadcrumbs::register('home', function($breadcrumbs) {
    $breadcrumbs->push('Home', route('home'));
});

4. I ran $php artisan config:publish davejamesmiller/laravel-breadcrumbs
However I used the default template. I changed nothing.

5. In my main layout, I included a footer contains this:
@yield('breadcrumbs')

6. I added something in my home view like this:
@extends('layouts.main')
... (some other sections)
@section('content') ... @stop
@section('breadcrumbs', Breadcrumbs::render('home'))

I ran the home page and I have this error message:

Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_UNKNOWN)
Call to undefined method DaveJamesMiller\Breadcrumbs\Facade::render()
Open: /var/www/Plaim/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php
 
		switch (count($args))
		{
			case 0:
				return $instance->$method();
 
			case 1:
				return $instance->$method($args[0]);
 
			case 2:

**Comment by anhuibl** [comment]
Hi, my supervisor have detect the problem.
I skept a step-2 in app/config/local/app.php. Because I am in local environment.

Thanks for all.

**Comment by davejamesmiller** [comment]
:+1:
