### ISSUE TITLE
Trying to get property of non-object with dynamic breadcrumbs

### ISSUE THREAD

**Issue by beregovoy** [davejamesmiller/laravel-breadcrumbs#72]
Hi. I need make a dynamic breadcrumbs for my news page.

Here is defining breadcrumb. And it's already not working.
```php
// Useful Articles. One article
Breadcrumbs::register('usefulArticles.article', function($breadcrumbs, $article)
{
    $breadcrumbs->parent('usefulArticles');
    $breadcrumbs->push('sdfsd', route('usefulArticles.article', ['id' => $article->id]));
});
````

Here is call
`@section('breadcrumbs', Breadcrumbs::render('usefulArticles.article', $article))`

$article is model of database. Which is `Article::find(1)` for example.

Here is the most interesting. If i made
```php
// Useful Articles. One article
Breadcrumbs::register('usefulArticles.article', function($breadcrumbs, $article)
{
    $breadcrumbs->parent('usefulArticles');
    dd($article);
    $breadcrumbs->push('sdfsd', route('usefulArticles.article', ['id' => $article->id]));
});
```
It will show me my model. But, if i will do `dd($article->id)` i will take `Trying to get property of non-object.`
I can read my object, but can't access to any of it's property. Can you help me with it?

**Comment by beregovoy** [comment]
I even can't access it as array. `Undefined index`

**Comment by beregovoy** [comment]
And by the way, does it possible use it like this?

_layouts.master.blade.php
`@yield('breadcrumbs', Breadcrumbs::render())`

And in some views
`@section('breadcrumbs', Breadcrumbs::render('usefulArticles.article', $article))`

**Comment by davejamesmiller** [comment]
Strange one - your code looks right to me. Can you show me the exact output of `dd($article)` and `dd($article->id)` so I can look closer at that?

Yes you can mix the two - though because of the way Laravel works the `Breadcrumbs::render()` method will always be called, even if you've specified a section in the view - so you may have to use `Breadcrumbs::renderIfExists()` to prevent an exception being thrown.

An alternative that lazy-loads, but is rather ugly, is:

```
@if(isset($__env->getSections()['breadcrumbs'])):
    @yield('breadcrumbs')
@else
    {!! Breadcrumbs::render() !!}
@endif
```

(http://stackoverflow.com/a/24583340)

Or you make it prettier by adding this service provider:

```php
<?php namespace App\Providers;

use Blade;
use Illuminate\Support\ServiceProvider;

class BladeServiceProvider extends ServiceProvider {

	/**
	 * Bootstrap the application services.
	 *
	 * @return void
	 */
	public function boot()
	{
		// e.g.
		// @ifSection('breadcrumbs')
		//   ...
		// @else
		//   ...
		// @endif
		Blade::extend(function($view, $compiler)
		{
			$pattern = $compiler->createMatcher('ifSection');

			return preg_replace($pattern, '$1<?php if (isset($__env->getSections()[$2])): ?>', $view);
		});
	}

	/**
	 * Register the application services.
	 *
	 * @return void
	 */
	public function register()
	{
		//
	}

}
```

And use this code:

```
@ifSection('breadcrumbs')
    @yield('breadcrumbs')
@else
    {!! Breadcrumbs::render() !!}
@endif
```

**Comment by beregovoy** [comment]
Probably problem was cause my breadcrumbs firstly was rendered in view, with passed $article, and second time it was called from layout without $article. So in this project i have not so much views, so i just maked render in each view. But in my next - i will try your solution. Thank you.
