### ISSUE TITLE
Same URL for registered breadcrumbs

### ISSUE THREAD

**Issue by virtous** [davejamesmiller/laravel-breadcrumbs#73]
Breadcrumbs version: 3
Laravel version: 5.1-dev
PHP version: 5.6.2
No error output.

Description: 
I have 6 registered crumbs, 2 static and 4 dynamic. The problem I'm having is that on the forum.comment.create route, the post has the same link as the category. I've attached 2 screenshots at the bottom to illustrate this. 

**Important note**: this package works perfectly on all pages except for the forum.comment.create route.

App/Http/routes.php
```
Route::get('/', ['as' => 'page.frontpage', 'uses' => 'PageController@frontpage']);
Route::get('/forum', ['as' => 'page.forum', 'uses' => 'CategoryController@index']);
Route::get('/forum/{category}', ['as' => 'forum.category.show', 'uses' => 'CategoryController@show']); 
Route::get('/forum/{category}/new', ['as' => 'forum.post.create', 'uses' => 'CategoryPostController@create']); 
Route::get('/forum/{category}/{post}', ['as' => 'forum.post.show', 'uses' => 'CategoryPostController@show']);
Route::get('/forum/{category}/{post}/comment', ['as' => 'forum.comment.create', 'uses' => 'CategoryPostCommentController@index']);
```

App/Http/breadcrumbs.php
```
// Dashboard
Breadcrumbs::register('page.frontpage', function($breadcrumbs)
{
    $breadcrumbs->push('Dashboard', route('page.frontpage'));
});


// Dashboard > Forum
Breadcrumbs::register('page.forum', function($breadcrumbs)
{
    $breadcrumbs->parent('page.frontpage');
    $breadcrumbs->push('Forum', route('page.forum'));
});


// Dashboard > Forum > [Category]
Breadcrumbs::register('forum.category.show', function($breadcrumbs, $categorySlug)
{
	$name = Category::where('slug', '=', $categorySlug)->first()->name;

    $breadcrumbs->parent('page.forum');
    $breadcrumbs->push($name, route('forum.category.show', $categorySlug));
});


// Dashboard > Forum > [Category] > Post Create
Breadcrumbs::register('forum.post.create', function($breadcrumbs, $categorySlug)
{
    $breadcrumbs->parent('forum.category.show', $categorySlug);
    $breadcrumbs->push('New Post');
});


// Dashboard > Forum > [Category] > [Post]
Breadcrumbs::register('forum.post.show', function($breadcrumbs, $categorySlug, $postSlug)
{
	$title = Post::where('slug', '=', $postSlug)->first()->title;

    $breadcrumbs->parent('forum.category.show', $categorySlug);
    $breadcrumbs->push($title, route('forum.post.show', $categorySlug, $postSlug));
});


// Dashboard > Forum > [Category] > [Post] > Comment Create
Breadcrumbs::register('forum.comment.create', function($breadcrumbs, $categorySlug, $postSlug)
{
    $breadcrumbs->parent('forum.post.show', $categorySlug, $postSlug);
    $breadcrumbs->push('Comment');
});
```

Config/breadcrumbs.php
```
return [

	'view' => 'partials/breadcrumbs',

];
```

View template (included in the master page)
Resources/views/partials/breadcrumbs.blade.php
```
@if ($breadcrumbs)
    <ul class="breadcrumb">
        @foreach ($breadcrumbs as $breadcrumb)
            @if (!$breadcrumb->last)
                <li><a href="{{{ $breadcrumb->url }}}">{{{ $breadcrumb->title }}}</a></li>
            @else
                <li class="active">{{{ $breadcrumb->title }}}</li>
            @endif
        @endforeach
    </ul>
@endif
```

Output
**The "test" crumb is actually the post. As you can see, it has the same url as the category. I want it to have `http://localhost.nounit/forum/news-and-announcements/test`**
![skarmavbild 2015-06-01 kl 00 41 27](https://cloud.githubusercontent.com/assets/3582546/7904387/8239aefe-07f8-11e5-9961-ae618547ef97.png)
![skarmavbild 2015-06-01 kl 00 43 45](https://cloud.githubusercontent.com/assets/3582546/7904388/85d6cef2-07f8-11e5-91b3-d5eebd452725.png)

**Comment by davejamesmiller** [comment]
Thanks for including all the detail.

Your code looks correct to me - but for some reason `route('forum.post.show', $categorySlug, $postSlug)` must be returning the wrong URL.

What's the code in the `forum.comment.create` controller (`CategoryPostCommentController@index`) and view?

What are the values of `$categorySlug`, `$postSlug` that are being passed into the breadcrumb - are they coming through correctly? You can find out with `dd()`:

```php
Breadcrumbs::register('forum.comment.create', function($breadcrumbs, $categorySlug, $postSlug)
{
    dd($categorySlug, $postSlug);
    $breadcrumbs->parent('forum.post.show', $categorySlug, $postSlug);
    $breadcrumbs->push('Comment');
});
```

If they are correct, I would try putting this in the breadcrumbs, controller and/or view:

```php
dd(route('forum.post.show', 'news-and-announcements', 'test'));
```

To see if you can work out what's causing it to return the wrong value.

HTH!

**Comment by virtous** [comment]
Hey Dave, thanks for that.

I did some checking and both `$categorySlug` and `$postSlug` are returning the correct values. 

Running `dd(route('forum.post.show', 'news-and-announcements', 'test'));` outputs
`"http://localhost.nounit/forum/news-and-announcements"` so the "test" string is not getting appended.

Inside my controller (CategoryPostComment@index) I have the following:
```
public function index($categorySlug, $postSlug)
{
	$category = Category::where('slug', '=', $categorySlug)->firstOrFail();

	$post = Post::where('slug', '=', $postSlug)->firstOrFail();

	return view('forum/create_reply', compact('post', 'category'));
}
```

if I do `dd($categorySlug, $postSlug)` inside the controller I get the correct values.

And finally in the view I have the following,

```
@extends ('forum')

@section ('forum-content')
	<div class="create-forum-reply p_a_c_c">	
		<div class="heading heading-md"><span>Comment on {{ $post->title }}</span></div>
		{!! Form::open(['route' => ['forum.comment.create', $category->slug, $post->slug], 'class' => 'form form-horizontal']) !!}
			@include('partials/errors')		
			<div class="row row-space">
				{!! Form::label('content', 'Content', ['class' => 'form-label']) !!}
				{!! Form::textarea('content', old('content'), ['class' => 'form-textarea']) !!}
			</div>

			<div class="row row-space">
				{!! Form::submit('Post Comment', ['class' => 'form-submit form-offset btn btn-primary']) !!}
			</div>
		{!! Form::close() !!}
	</div>
@endsection
```

Any suggestions on where I should start debugging?

**Comment by virtous** [comment]
**Problem Solved**

The problem lay in the `route()` function. I was simply passing in my values incorrectly.

`vendor/laravel/framwork/src/Illuminate/Foundation/helpers.php@487`, the function takes in an array of params to pass in so I was able to fix everything by adding square brackets when pushing multiple values.

 `$breadcrumbs->push($title, route('forum.post.show', [$categorySlug, $postSlug]));`

You might want to consider adding a short example of this inside the docs or a link to the `route` function.

Thanks again.

**Comment by davejamesmiller** [comment]
Ah, I didn't spot that.

I can't find any explanation in the Laravel docs(!), so I've added some extra examples here:
http://laravel-breadcrumbs.davejamesmiller.com/en/latest/defining.html#static-pages
