### ISSUE TITLE
Class 'Breadcrumbs' not found

### ISSUE THREAD

**Issue by muhghazaliakbar** [davejamesmiller/laravel-breadcrumbs#75]
i have error Class 'Breadbrumbs' not found in my laravel 5.1 aplication. i follow instruction in documentation, but still error.

**Comment by davejamesmiller** [comment]
See https://github.com/davejamesmiller/laravel-breadcrumbs/blob/master/CONTRIBUTING.rst

**Comment by muhghazaliakbar** [comment]
im sorry :) 

here my errors

![screenshot_149](https://cloud.githubusercontent.com/assets/8321936/9316548/4689c472-4568-11e5-8329-e17150c56412.png)

breadcrumbs version
"davejamesmiller/laravel-breadcrumbs": "^3.0"

laravel version: 5.1
php version: 5.5.9

and my config/app.php
![screenshot_150](https://cloud.githubusercontent.com/assets/8321936/9316611/ac5bf2de-4568-11e5-92e5-885d680a9fce.png)
![screenshot_151](https://cloud.githubusercontent.com/assets/8321936/9316612/ac62749c-4568-11e5-86ac-3fb352801c8e.png)

and this is breadcrumbs.php in app\Http
![screenshot_152](https://cloud.githubusercontent.com/assets/8321936/9316643/cdd94042-4568-11e5-866e-07f9ad16f692.png)

**Comment by davejamesmiller** [comment]
Either remove `namespace Vomesia\Http;` from the top of the file, or add `use Breadcrumbs;`.

**Comment by muhghazaliakbar** [comment]
i've added use Breadcrumbs; but still no effect.
![screenshot_153](https://cloud.githubusercontent.com/assets/8321936/9317111/04252398-456c-11e5-963b-51bb32cff7e0.png)

**Comment by davejamesmiller** [comment]
That looks OK now - though you don't really need to do both the things I said just one of them.

Looking closer at the error, it has a random filename. I think that means it's an error in one of the views rather than the breadcrumbs file - but you didn't include those so I can't look...

**Comment by muhghazaliakbar** [comment]
oh im sorry, forget to attach my view,

here my view:
![screenshot_154](https://cloud.githubusercontent.com/assets/8321936/9317345/8a2ce0c4-456d-11e5-8673-96cbe156371d.png)

**Comment by davejamesmiller** [comment]
What's above that? Again I'm looking for namespaces or anything else that might cause it not to find the class...

**Comment by muhghazaliakbar** [comment]
this is my view,

and here complete line 7 error.
![screenshot_155](https://cloud.githubusercontent.com/assets/8321936/9317891/21cbffe8-4571-11e5-87f8-47b7e584bfea.png)
![screenshot_156](https://cloud.githubusercontent.com/assets/8321936/9317905/3d4f67aa-4571-11e5-9452-ba67fc302ea7.png)

and i don't know anything else where my mistake

**Comment by muhghazaliakbar** [comment]
Hi @davejamesmiller i've changed my app namespace to default and worked fine. if not able to use the costume namespace in the application?

**Comment by davejamesmiller** [comment]
Strange one. I can't think of any reason why that would be - it doesn't use the namespace anywhere that I know of.

**Comment by noncototient** [comment]
Had this problem happen when deploying Laravel app to production app. 

**Specs:**
Laravel 5.3 
PHP 5.6
Ubuntu 14
Breadcrumbs 3.0

Checked all class names for capitalisation issues, folders names, facades, etc and nothing seemed to fix the problem.

However, running the following artisan commands on the production server fixed it:

```
php artisan cache:clear
php artisan config:clear
```

**Comment by Under-Warz** [comment]
@noncototient try this command when deploy finished 

`php artisan clear-compiled`

worked for me. If didn't, try all the other clean commands like 
`php artisan optimize
php artisan config:cache
php artisan route:cache
...
`
