### ISSUE TITLE
Nested Breadcrumb problem

### ISSUE THREAD

**Issue by Woutje99** [davejamesmiller/laravel-breadcrumbs#76]
Hi,

I can't find a solution for my problem.

I have a website with some pages.
Like: Home/about-us/about

I want to show a breadcrumb like this: Home / About Us / About
The pages are dynamically build, I read the documentation by Nested Categories but I don't get it right in my application.

The pages About Us and About are dynamically build.

The Breadcrumb is showing this when I rendering: Home / About
But i want Home / About Us / About
Can you help me?

This is my breadcrumb code:
```
Breadcrumbs::register('page', function($breadcrumbs, $page) {
  if ($page->parent){
        $breadcrumbs->parent('page', $page->parent);
    }
    else{
      $breadcrumbs->parent('home');
    }
    $breadcrumbs->push($page->title, route('page', $page->slug));
});
```
And this is my route for it: 
```
Route::get('/{name}/{identifier?}', array('as' => 'page', 'namespace' => 'Pages', 'uses' => 'PagesController@index'));
```

**Comment by davejamesmiller** [comment]
Sounds like `$page->parent` isn't working... Try using `dd($page->parent)` to debug it - make sure it returns the parent page properly.

**Comment by Woutje99** [comment]
When I ```dd($page->parent)``` It returns null..
But how can I set that parent?

**Comment by davejamesmiller** [comment]
That's entirely up to you. It depends on your database structure and your Eloquent model.

**Comment by Woutje99** [comment]
Hmmm I get it.
I have solved the problem!
