### ISSUE TITLE
Auth::user() is null

### ISSUE THREAD

**Issue by struyfv** [davejamesmiller/laravel-breadcrumbs#77]
When I dump Auth::user(), I receive null, when I'm logged in. Why is the user empty in breadcrumbs.php?

**Comment by davejamesmiller** [comment]
No idea. Are you putting it into breadcrumbs.php directly or into one of the callback functions? If the former, maybe that happens too early in the bootstrap process? Just guessing though.

**Comment by struyfv** [comment]
I'm putting an if around a Breadcrumbs::register to check who the user is. The breadcrumbs are different for some users. But Auth::user is null. Any idea how I can fix this?

**Comment by davejamesmiller** [comment]
Put it inside the callback not outside?

**Comment by Gummibeer** [comment]
For the routes.php the solution will be a middleware - cause, my last stand, the Auth::User() Object isn't present in the routes.php (the Object get initialized after the Middleware and before the Contoller.
The breadcrumbs.php is something similar to the routes.php - so I think that the Object is simply not present. You can try to create this Object by your own - catch the session/cookie, look for a User and so on - http://laravel.com/docs/5.1/authentication#authenticating-users
The other solution is, if it is possible, to use a middleware.
But I don't know wich side-effects these solutions can bring or if there are better solutions.

**Comment by struyfv** [comment]
no difference with Auth::User() or \Auth::User(). But when I put it inside, it works

**Comment by davejamesmiller** [comment]
I think if you're trying to use `Auth::user()` in the top level of either routes.php or breadcrumbs.php you're probably doing something wrong. If you do it in the routes, this will prevent you using [route caching](http://laravel.com/docs/5.0/controllers#route-caching), and `php artisan routes` won't display all routes. Breadcrumbs doesn't have either of these currently, but the principle is the same. Put the logic inside the callback instead.
