### ISSUE TITLE
Missing Argument Error

### ISSUE THREAD

**Issue by fadifannoun** [davejamesmiller/laravel-breadcrumbs#78]
I am trying to pass a third param to the render function but keep git this error:

```
Missing argument 3 for DaveJamesMiller\Breadcrumbs\ServiceProvider::{closure}()
```

Here is how I call breadcrumb
```
{{ Breadcrumbs::render( 'category', $catObject, $pageInfo) }}
````

And here is the code snippet to handle registration

```
Breadcrumbs::register('category', function($breadcrumbs, $category, $page) {
});
```

Best

**Comment by davejamesmiller** [comment]
https://github.com/davejamesmiller/laravel-breadcrumbs#support-requests--bug-reports

**Comment by davejamesmiller** [comment]
What you posted looks fine to me. Closing since you've not provided any of the extra detail asked for in the readme.

**Comment by szabizs** [comment]
I had the same problem before realizing that in my breadcrumb function i had a parent(recursive), so you have to pass all the parameters to the parent.
