### ISSUE TITLE
Structured Data

### ISSUE THREAD

**Issue by PatSpiegel** [davejamesmiller/laravel-breadcrumbs#79]
maybe add Structured Data?
https://developers.google.com/structured-data/breadcrumbs

**Comment by davejamesmiller** [comment]
Sounds like a good idea. Not high on my priority list, but PR or ideas for implementation welcome.

**Comment by tutNichts** [comment]
I just extended the package with an own service provider to realize this, but's just a work around. So, yes, would be great!

**Comment by davejamesmiller** [comment]
**Laravel Breadcrumbs is no longer officially maintained**
Please [see the README file](https://github.com/davejamesmiller/laravel-breadcrumbs/blob/master/README.rst) for further details.
