### ISSUE TITLE
Route $name not defined when using route:cache

### ISSUE THREAD

**Issue by raydric** [davejamesmiller/laravel-breadcrumbs#80]
Any idea why it stops working **only** when I use `artisan route:cache`? I get a
`InvalidArgumentException in UrlGenerator.php line 278: Route [my.route.name] not defined.`

The content of the cached routes are fine but they aren't visible when I dump the route list on the breadcrumbs.php file.
Output (`Route::getroutes()`):
`RouteCollection {#26 ▼
  #routes: []
  #allRoutes: []
  #nameList: []
  #actionList: []
}`

But in the other files I get the correct values (I can see the named routes in the RouteCollection).

Am I doing something wrong? BTW moving the breadcrumbs declaration to my controller makes everything work again. Changing defer to true or false doesn't. My breadcrumbs service provider is also declared after everything else (`app.config`).

`PHP 5.5.9-1ubuntu4.11` `"laravel/framework": "5.1.*"` `"davejamesmiller/laravel-breadcrumbs": "^3.0"`

**Comment by davejamesmiller** [comment]
I've not used the route cache myself, but I think it should work fine.

If you're putting `Router::getRoutes()` in the top-level of `breadcrumbs.php` and not in one of the callbacks, it's possible that it gets run before the routes are loaded.

If you want more help than that, please include full copies of the code you're using.
