### ISSUE TITLE
Breadcrumb not found with name

### ISSUE THREAD

**Issue by Jok3r11of** [davejamesmiller/laravel-breadcrumbs#81]
```Breadcrumb not found with name "cabinet.index"```
get this error.
laravel version 5.1
My routes:
```Route::get('/', ['as' => 'home', 'uses' => 'HomeController@index' ]);
Route::get('cabinet', ['as'=>'cabinet.index', 'uses' => 'CabinetController@index' ]);```
app/http/breadcrubms.php
```<?php
Breadcrumbs::register('home', function($breadcrumbs){
    $breadcrumbs->push('Home', route('home'));
});
Breadcrumbs::register('cabinet.index', function($breadcrumbs){
	$breadcrumbs->parent('home');
    $breadcrumbs->push(trans('words.cabinet'), route('cabinet.index'));
});
 ```
Any suggestions please?
or I can't use a dot seperated name for routes?

**Comment by Jok3r11of** [comment]
Very strange:
added a close php tag ```?>``` in ```app/http/breadcrubms.php``` and now is working.

**Comment by davejamesmiller** [comment]
I assume you spelled `breadcrumbs.php` correctly? You used `breadcrubms.php` in both messages.

Strange that that caused it to work - it shouldn't make any difference how the file is formatted. Maybe it just wasn't saved properly the first time?

Anyway, glad you got it working.

**Comment by Jok3r11of** [comment]
@davejamesmiller 
Yes the filename is ```breadcrumbs.php````
Made mistake in comment
Yes thank you for the package

**Comment by fureszk** [comment]
I ran into the same error after upgrading to Laravel 5.5 and Laravel Breadcrumbs 2.4.x:
I had to move my breadcrumbs.php file from config/ to routes/
