### ISSUE TITLE
Add a method to access registered breadcrumbs

### ISSUE THREAD

**Issue by robjbrain** [davejamesmiller/laravel-breadcrumbs#85]
When accessing breadcrumbs the only methods available return arrays, this is fine for lopping in a single breadcrumb template, but it would be great to have easier access to the breadcrumbs for potential use in other places

For instance the possible use I just came across was automatically setting the meta canonical and title to the last breadcrumb if it wasn't otherwise set e.g. 

```
@if(isset($title))
    <title>{{ $title }}</title>
@else
    <title>{{ $breadcrumbs->last()->title }}</title
@endif
```

This would avoid setting the title of the page twice in lots of places (it's often the same string) but also keeps it really simple to overwrite.

There might be other use cases, you don't need to subscribe to that one, my only point at the moment is that it's difficult to access the breadcrumbs other than in a foreach loop.

**Comment by davejamesmiller** [comment]
I think this is pretty similar to #82, which reportedly works but is missing unit tests and documentation so I haven't merged it yet.

**Comment by davejamesmiller** [comment]
**Laravel Breadcrumbs is no longer officially maintained**
Please [see the README file](https://github.com/davejamesmiller/laravel-breadcrumbs/blob/master/README.rst) for further details.

**Comment by davejamesmiller** [comment]
I’ve decided to [start working on Laravel Breadcrumbs again](https://davejamesmiller.com/2017/06/24/laravel-breadcrumbs-redux).

This will be [added in v4](https://github.com/davejamesmiller/laravel-breadcrumbs/pull/140) as `Breadcrumbs::current()`.
