### ISSUE TITLE
artisan route:list prints out error from breadcrumbs.php

### ISSUE THREAD

**Issue by csuarezgfx** [davejamesmiller/laravel-breadcrumbs#87]
Hi Dave, first thank you for a great breadcrumbs package. I am having an issue with artisan route:list caused by what I think is the breadcrumbs file. Please read this thread from Laracasts.com which explains the entire problem.

https://laracasts.com/discuss/channels/laravel/routelist-command-is-producing-error

Thanks again!

**Comment by davejamesmiller** [comment]
Replied on the forum :)
