### ISSUE TITLE
Custom template not working

### ISSUE THREAD

**Issue by hulu8004** [davejamesmiller/laravel-breadcrumbs#88]
It's saying that I'm missing the `$breadcrumbs` variable... yet when I take a look at the predefined templates, it has the same thing but it works. Is there something I'm missing?

Here's the errors I'm getting when trying to use a custom template:

![screencapture-laravel-dev-1446756366983](https://cloud.githubusercontent.com/assets/5089787/10981211/7470df24-83d4-11e5-9994-f75b474ca5d2.png)

**Laravel Breadcrumbs Version** - 3.0 (I got this from composer.json)
**Laravel Version** - 5.1 (Also from composer.json)
**PHP Version** - 5.6

`app\Http\breadcrumbs.php` - https://gist.github.com/hulu8004/a13f17dca770fefc45f1
`config/breadcrumbs.php` - https://gist.github.com/hulu8004/03be52df3d9e80219760
`resources/views/front/partials/breadcrumbs.blade.php` - https://gist.github.com/hulu8004/4ea4ca79f4876e0ce813
`config/app.php` - https://gist.github.com/hulu8004/2de28a2818231c2962a4

If you need anything else please let me know, I've been stuck on this for **HOURS** trying to figure it out myself.

Thanks!

**Comment by davejamesmiller** [comment]
In `config/breadcrumbs.php` you have `'view' => '_partials.breadcrumbs',` not `front.partials.breadcrumbs`. My guess is you've got `@include('front.partials.breadcrumbs')` in your header instead of `Breadcrumbs::render()` ? If not, please fix the config file and show me the header file too.

**Comment by hulu8004** [comment]
That fixed it, I thought it was using the template from the custom file, I didn't know that I had to `render()` the breadcrumbs. Thanks!

**Comment by davejamesmiller** [comment]
:+1:
