### ISSUE TITLE
Connection Reset?

### ISSUE THREAD

**Issue by hulu8004** [davejamesmiller/laravel-breadcrumbs#89]
I have the same setup as the last issue I posted: https://github.com/davejamesmiller/laravel-breadcrumbs/issues/88

But now when I add `$breadcrumbs->parent( 'home', route('home') );` it gives me **ERR_CONNECTION_RESET** (in chrome).

I've checked the logs and it doesn't show any errors.

**Comment by davejamesmiller** [comment]
That's not valid - `parent()` doesn't take a route parameter. My guess is you're causing an infinite loop by calling `parent` from the `home` route. If not, please paste the full code you're using now.

**Comment by hulu8004** [comment]
Umm according to the documentation it's correct:

    // Home > [Page]
    Breadcrumbs::register('page', function($breadcrumbs, $id)
    {
        $page = Page::findOrFail($id);
        $breadcrumbs->parent('home');
        $breadcrumbs->push($page->title, route('page', $page->id));
    });

**Comment by hulu8004** [comment]
This is what my `breadcrumbs.php` file has in it
    // Home
    Breadcrumbs::register( 'home', function( $breadcrumbs )
    {
        $breadcrumbs->parent('home');
        $breadcrumbs->push('News');
    });

**Comment by davejamesmiller** [comment]
As I suspected, you're causing an infinite loop by calling `$breadcrumbs->parent('home');` from the `home` route. Just remove that line completely.
